### ISSUE TITLE
time between image change - specific time of day & 1-24hr selection

### ISSUE THREAD

**Issue by Symbiot78** [dakboard/Cloud-Platform#20]
Hi

would be great to have the option to set multiple specific times during the day where the image changes..

say I want the image to change at 6 in the morning and then again at 6 in the evening

Or specifically at 12:45, 13:45: 14:45 etc.
Or 12:15, 1500, 1725, 2109 etc.

AND.. add more selections to the "time between...." so, 1,2,3,4,5,6,7,-----> hrs

**Comment by cocarrig** [comment]
Hi,

We recommend creating separate photo blocks and configuring schedules available in the block configuration to show photos from separate sources at this time.

Unfortunately we have reviewed this request and made a determination not to move forward due to insufficient customer interest.

If you have any comments or concerns please reach out to us at support@dakboard.com.
